templates:
  collection:
    default:
      collection_order: release
      minimum_items: 2
    optional:
      - collection
      - movie
      - name_mapping
      - sort_title
      - build_collection
      - item_label
    cache_builders: 1
    minimum_items: <<minimum_items>>
    tmdb_collection_details: <<value>>
    tmdb_movie: <<movie>>
    name_mapping: <<name_mapping>>
    sort_title: <<sort_title>>
    build_collection: <<build_collection>>
    sync_mode: sync
    collection_order: <<collection_order>>
    item_label: <<item_label>>

dynamic_collections:
  TMDb Collections:
    type: tmdb_collection
    remove_prefix: The
    remove_suffix: Collection
    template: collection

#    exclude:
#      - 374509  # Godzilla (Showa)

#    addons: # combine collections
#      8091:       # Alien
#        - 135416    # Prometheus

    title_override:
      263: The Dark Knight
      119: The Lord of the Rings

    template_variables:

#      movie: # what movies should be part of collections but TMDB doesn't agree?
#        2980:       # Ghostbusters
#          - 43074     # Ghostbusters 2016

      name_mapping: # where does the folder name not match the collection name?
                    # must include any where title_override value starts with "The"
        263: Dark Knight
        119: Lord of the Rings

      item_label:
        535313: MonsterVerse
        119: LOTR,Middle-Earth
        
      collection_order:
        2344: alpha   # The Matrix

      minimum_items:
        529892: 1     # Black Panther
        
