templates:
  tmdb:
    optional:
      - collection
      - show
    tmdb_collection: <<collection>>
    tmdb_show: <<show>>
    sync_mode: sync
    collection_order: release
    move_prefix: The,A
  tmdb_or_tag:
    optional:
      - collection
      - show
      - tag
    tmdb_collection_details: <<collection>>
    tmdb_show: <<movie>>
    plex_search:
      all:
        label: <<tag>>
    summary: <<summary>>
    sync_mode: sync
    collection_order: release
    move_prefix: The,A

collections:
#  "Sarah's Watchlist Source":
#    trakt_list: https://trakt.tv/users/tomhenrich/lists/sarah-s-netflix?sort=title,asc
#    smart_label: title.asc
#    sort_title: "zSarahs Watchlist"
#    item_label: SarahsWatchlist
#    build_collection: false
  "Sarah's Watchlist":
    trakt_list: https://trakt.tv/users/tomhenrich/lists/sarah-s-netflix?sort=title,asc
    smart_label:
      all:
        unplayed_episodes: true
      sort_by: title.asc
    sort_title: "+Sarahs Watchlist"
    name_mapping: Sarahs Watchlist
    label: noshare
   
  "Battlestar Galactica (Reboot)":
    sort_title: Battlestar Galactica 2003
    summary: A re-imagining of the original series in which a "rag-tag fugitive fleet" of the last remnants of mankind flees pursuing robots while simultaneously searching for their true home, Earth.
    minimum_items: 1
    plex_search:
      all:
        label:
          - Battlestar
          - Reboot
  Middle Earth:
    template: {name: tmdb, show: 84773}
    minimum_items: 1
    collection_mode: hide
  Serenity:
    template: {name: tmdb, show: 1437}
    minimum_items: 1
    collection_mode: hide
  Stargate:
    template: {name: tmdb, show: "4629, 2290, 5148, 72925"}
    summary: "The missions and adventures of teams sent through an ancient alien wormhole network."
  Star Trek:
    template: {name: tmdb, show: "253, 655, 1855, 314, 67198, 85949, 103516"}
    minimum_items: 1
  Star Wars:
    template: {name: tmdb, show: "92830, 115036, 82856"}
    minimum_items: 1
  Twilight Zone:
    template: {name: tmdb, show: "6357, 1918, 83135, 16399"}
