metadata:
  "Battlestar Galactica (1978)":
    alt_title: "Battlestar Galactica"
    title: "Battlestar Galactica (1978)"
    year: 1978
    tmdb_show: 501
    label.sync: Battlestar Galactica
  Battlestar Galactica 2003:
    alt_title: "Battlestar Galactica"
    title: "Battlestar Galactica (Miniseries)"
    year: 2003
    tmdb_show: 71365
    tvdb_show: 73545
    label.sync: Battlestar Galactica,Reboot
  Battlestar Galactica 2004:
    title: Battlestar Galactica
    year: 2004
    tmdb_show: 1972
    tvdb_show: 73545
    label.sync: Battlestar Galactica,Reboot
  Mystery Science Theater 3000:
    summary: "Joel Robinson is held captive by mad scientists, forced to watch B-Grade movies with his robot friends. (Limited episode availability due to haphazard DVD releases.)"
