metadata:
  Battlestar Galactica (1978):
    match:
      title: Battlestar Galactica
      year: 1978
    sort_title: Battlestar Galactica 1978
  Battlestar Galactica (Reboot):
    match:
      title: Battlestar Galactica
      year: 2003
    title: Battlestar Galactica (Reboot)
    sort_title: Battlestar Galactica 2003
  Firefly:
    match:
      mapping_id: 78874
      title: Firefly
    episode_ordering: tvdb_absolute
  Mystery Science Theater 3000:
    match:
      mapping_id: 74806
    summary: "Joel Robinson is held captive by mad scientists, forced to watch B-Grade movies with his robot friends. (Limited episode availability due to haphazard DVD releases.)"
