metadata:
  "Battlestar Galactica (1978)":
    title: "Battlestar Galactica"
    year: 1978
    tmdb_show: 501
  "Battlestar Galactica (Miniseries)":
    title: "Battlestar Galactica"
    year: 2003
    tmdb_show: 71365
  "Battlestar Galactica": # 4-season show
    title: "Battlestar Galactica (2004"
    year: 2004
    tmdb_show: 1972
