metadata:
  Battlestar Galactica (1978):
    match:
      mapping_id: 71173
    sort_title: Battlestar Galactica 1978
  Battlestar Galactica (Reboot):
    match:
      mapping_id: 73545
    sort_title: Battlestar Galactica 2003
  Firefly:
    match:
      mapping_id: 78874
      title: Firefly
    episode_ordering: tvdb_absolute
  Lost:
    match:
      mapping_id: 73739
      title: Lost
    episode_ordering: tvdb_dvd
  Invasion (2021):
    match:
      mapping_id: 404492
    title: Invasion
