templates:
  tmdb:
    optional:
      - collection
      - movie
    tmdb_collection_details: <<collection>>
    tmdb_movie: <<movie>>
    sync_mode: sync
    collection_order: release
    move_prefix: The,A
  tmdb_or_tag:
    optional:
      - collection
      - movie
      - tag
    tmdb_collection_details: <<collection>>
    tmdb_movie: <<movie>>
    plex_search:
      all:
        label: <<tag>>
    sync_mode: sync
    collection_order: release
    move_prefix: The,A
  tmdb_keyword:
    tmdb_keyword: <<keyword>>
    sync_mode: sync
    collection_order: release
    move_prefix: The,A

#
# CURATED COLLECTIONS
# Curated -- either not official TMDB collections, or specific combinations of movies
#
collections:
  Cloverfield:
    template: {name: tmdb, movie: "7191, 333371, 384521"}
  Eastrail 177:
    template: {name: tmdb, movie: "9741, 381288, 450465"}
    summary: "A superhero thriller and psychological horror film series involving the derailment of the fictitious Eastrail 177 train."
  I Am Legend:
    template: {name: tmdb, collection: 945984, movie: "21159, 11234, 6479"}
    summary: "Films adapted from the novel I AM LEGEND by Richard Matheson."
  Kurosawa Samurai:
    template: {name: tmdb, movie: "548, 346, 3777, 1059, 11878, 11712, 11953, 11645"}
    summary: "Samurai films by the legendary Japanese director, Akira Kurosawa."
    item_label: Samurai
  The Manchurian Candidate:
    template: {name: tmdb, movie: "982, 14462"}
    name_mapping: Manchurian Candidate
    summary: "Film adaptations of Richard Condon's 1959 novel about an American who is brainwashed into being an unwitting assassin."
  Serenity:
    template: {name: tmdb, movie: 16320}
    minimum_items: 1
    collection_mode: hide

  Godzilla:
    trakt_list_details: https://trakt.tv/users/tomhenrich/lists/godzilla?sort=rank,asc
    summary: "The King of the Monsters."
    collection_order: custom
    item_label: Godzilla
    sort_title: "Godzilla +"

  "Godzilla (Showa Era)":
    template: {name: tmdb, collection: 374509}
    item_label: Godzilla,GodzillaClassic,GodzillaShowa
    build_collection: false
  "Godzilla (Heisei Era)":
    template: {name: tmdb, collection: 374511}
    item_label: Godzilla,GodzillaClassic,GodzillaHeisei
    build_collection: false
  "Godzilla (Millennium Era)":
    template: {name: tmdb, collection: 374512}
    item_label: Godzilla,GodzillaClassic,GodzillaMillennium
    build_collection: false

  Star Trek:
    template:
      name: tmdb
      collection:
        - 151
        - 115570
        - 115575
    item_label: Star Trek
    summary: "All films from the iconic Star Trek franchise."

  Studio Ghibli:
    template: {name: tmdb}
    trakt_list_details: https://trakt.tv/users/draackje/lists/studio-ghibli-feature-films?sort=released,asc
    item_label: Ghibli
  Toho Extended Universe:
    trakt_list_details: https://trakt.tv/users/jaygreene/lists/godzilla-toho-extended-universe?sort=released,desc
    item_label: "Toho EU"
    collection_mode: hide
    build_collection: false
  Universal Monsters:
    template:
      name: tmdb
      collection:
        - 221539
        - 218406
        - 259401
        - 221544
        - 259027
        - 221537
      movie:
        - 15855
        - 27970
        - 24106
        - 17907
        - 106296
        - 84719
        - 45322
    summary: "Showcasing the most iconic monsters in motion picture history, including Dracula, Frankenstein's Monster, the Mummy, the Invisible Man, the Wolf Man, and more!"
  Vengeance Trilogy:
    tmdb_list: https://www.themoviedb.org/list/8238285

########################################
# Marvel Movies
########################################
  Black Widow:
    template: {name: tmdb, movie: 497698}
    minimum_items: 1
  Incredible Hulk:
    template: {name: tmdb, movie: 1724}
    item_label: MCU
    minimum_items: 1
  Spider-Man:
    template:
      name: tmdb
      collection:
        - 556     # Maguire
        - 125574  # Garfield
        - 531241  # Holland (Avengers)
        - 573436  # Spider-Verse
    summary: "Films starring the Marvel Comics character Peter Parker, who gains spider-like abilities and learns that with great power comes great responsibility."
    item_label: Spider-Man
    test: true


  MCU:
    build_collection: false
    template:
      name: tmdb
      collection:
        - 422834
        - 86311
        - 529892
        - 131295
        - 623911
        - 618529
        - 1011336
        - 284433
        - 131292
        - 912503
        - 531241
        - 131296
      movie:
        - 497698
        - 1724
        - 894205
  MCEU:
    build_collection: false
    trakt_list:
      - https://trakt.tv/users/asterlea/lists/marvel?display=movie&sort=release,asc
    item_label: MCEU

########################################
# DC Movies
########################################

  DC Universe:
    trakt_list: 
      - https://trakt.tv/users/zosoleary/lists/dc-cinematic-universe
      - https://trakt.tv/users/malicekodi2/lists/dc
      - https://trakt.tv/lists/20583443
    smart_label:
      all:
        label: <<smart_label>>
      sort_by: release.asc
    minimum_items: 1
    item_label: DCU

########################################
# SMART COLLECTIONS
########################################

  "Tom's Watchlist":
    trakt_list: https://trakt.tv/users/tomhenrich/watchlist?sort=rank,asc
    smart_label:
      all:
        label: <<smart_label>>
        unplayed: true
    sort_title: "+Toms Watchlist"
    name_mapping: Toms Watchlist
    label: noshare
    minimum_items: 1

  "Sarah's Watchlist":
    trakt_list: 
      - https://trakt.tv/users/tomhenrich/lists/sarah-s-watchlist?sort=title,asc
      - https://trakt.tv/users/nursesawa/watchlist?sort=rank,asc
    smart_label:
      all:
        label: <<smart_label>>
        unplayed: true
      sort_by: title.asc
    sort_title: "+Sarahs Watchlist"
    name_mapping: Sarahs Watchlist
    label: noshare
    minimum_items: 1

  Non-English:
    smart_filter:
      any:
        audio_language.not: English
      sort_by: title.asc
    sort_title: "++Non-English"

  "Godzilla (Classic Era)":
    smart_filter:
      all:
        label: GodzillaClassic
      sort_by: release.asc
    summary: "Godzilla movies from the Showa (1954–1975), Heisei (1984–1995), and Millennium eras (1999-2004)."
    name_mapping: "Godzilla Classic"
    sort_title: "Godzilla Classic"
    collection_mode: hide

  Hitchcock:
    plex_search:
      all:
        director: Alfred Hitchcock
    collection_order: release
    collection_mode: hide_items

  Marvel Cinematic Universe:
    smart_filter:
      any:
        label: MCU
      sort_by: release.asc

  Middle Earth:
    smart_label: title.asc
    tmdb_collection:
      - 119
      - 121938
    item_label.append: Middle Earth
    summary: "J.R.R. Tolkien's fantasy series following the adventures of Bilbo and Frodo Baggins." 

  MonsterVerse:
    smart_filter:
      any:
        label: MonsterVerse
      sort_by: title.asc
    summary: The MonsterVerse is an American multimedia franchise and shared fictional universe featuring Godzilla, King Kong, and other Toho monster characters.

  "Spider-Man (Raimi Trilogy)":
    tmdb_collection_details: 556
    name_mapping: "Spider-Man (Raimi)"
    smart_label: title.asc
    sort_title: "Spider-Man 2002"
    collection_mode: hide
    test: true
  The Amazing Spider-Man:
    tmdb_collection_details: 125574
    name_mapping: Amazing Spider-Man
    smart_label: title.asc
    sort_title: "Spider-Man 2012"
    item_label: MCEU,Spider-Man
    collection_mode: hide
    test: true
  "Spider-Verse":
    tmdb_collection_details: 573436
    smart_label: title.asc
    item_label: MCEU,Spider-Man
    collection_mode: hide
    minimum_items: 1
    test: true


  "Star Trek: TOS":
    tmdb_collection_details: 151
    smart_label: title.asc
    sort_title: "Star Trek C1: TOS"
    item_label: Star Trek, Star Trek TOS
    name_mapping: Star Trek TOS
    collection_mode: hide

  "Star Trek: TNG":
    tmdb_collection_details: 115570
    smart_label: title.asc
    sort_title: "Star Trek C2: TNG"
    item_label: Star Trek, Star Trek TNG
    name_mapping: Star Trek TNG
    collection_mode: hide

  "Star Trek: Kelvin Timeline":
    tmdb_collection_details: 115575
    smart_label: title.asc
    sort_title: "Star Trek C3: Kelvin"
    item_label: Star Trek, Star Trek KEL
    name_mapping: Star Trek Kelvin
    collection_mode: hide

  Toho Kaiju:
    plex_search:
      all:
        label: "Toho EU"
        label.not: Godzilla
    minimum_items: 1


  Marvel Extended Universe:
    smart_filter:
      any:
        label: MCEU
      sort_by: title.asc
    summary: Movies based on Marvel properties but not officially part of the Marvel Cinematic Universe.

