templates:
  tmdb:
    optional:
      - collection
      - movie
    tmdb_collection_details: <<collection>>
    tmdb_movie: <<movie>>
    sync_mode: sync
    collection_order: release
    move_prefix: The,A
  tmdb_or_tag:
    optional:
      - collection
      - movie
      - tag
    tmdb_collection_details: <<collection>>
    tmdb_movie: <<movie>>
    plex_search:
      all:
        label: <<tag>>
    sync_mode: sync
    collection_order: release
    move_prefix: The,A
  tmdb_keyword:
    tmdb_keyword: <<keyword>>
    sync_mode: sync
    collection_order: release
    move_prefix: The,A

#
# MANUALLY CREATED COLLECTIONS
# Curated -- either not official TMDB collections, or specific combinations of movies
#
collections:
  Battlestar Galactica:
    template: {name: tmdb, collection: 91697}
    summary: "Follows the trials of the Colonial Fleet vessel Battlestar Galactica as it leads the last remaining humans on a search for Earth."
  Cloverfield:
    template: {name: tmdb, movie: "7191, 333371, 384521"}
  Eastrail 177:
    template: {name: tmdb, movie: "9741, 381288, 450465"}
    summary: "A superhero thriller and psychological horror film series involving the derailment of the fictitious Eastrail 177 train."
  "Godzilla: King of the Monsters":
    template: {name: tmdb, collection: "374509, 374511, 374512, 535790, 535313", movie: "929, 315011"}
    summary: "The King of the Monsters."
    collection_order: title.asc
    item_label: Godzilla
    name_mapping: Godzilla
    sort_title: "Godzilla (0)"
  I Am Legend:
    template: {name: tmdb, collection: 945984, movie: "21159, 11234, 6479"}
    summary: "Films adapted from the novel I AM LEGEND by Richard Matheson."
  Kurosawa Samurai:
    template: {name: tmdb, movie: "548, 346, 3777, 1059, 11878, 11712, 11953, 11645"}
    summary: "Samurai films by the legendary Japanese director, Akira Kurosawa."
    item_label: Samurai
  The Manchurian Candidate:
    template: {name: tmdb, movie: "982, 14462"}
    name_mapping: Manchurian Candidate
    summary: "Film adaptations of Richard Condon's 1959 novel about an American who is brainwashed into being an unwitting assassin."
  Serenity:
    template: {name: tmdb, movie: 16320}
    minimum_items: 1
    collection_mode: hide
  Star Trek:
    template:
      name: tmdb
      collection:
        - https://www.themoviedb.org/collection/151-star-trek-the-original-series-collection
        - https://www.themoviedb.org/collection/115570-star-trek-the-next-generation-collection
        - https://www.themoviedb.org/collection/115575-star-trek-alternate-reality-collection
    item_label: Star Trek
    summary: "All films from the iconic Star Trek franchise."
  Star Wars:
    template:
      name: tmdb
      collection:
        - https://www.themoviedb.org/collection/10-star-wars-collection
      movie:
        - https://www.themoviedb.org/movie/330459-rogue-one-a-star-wars-story
        - https://www.themoviedb.org/movie/348350-solo-a-star-wars-story
        - https://www.themoviedb.org/movie/74849-star-wars-holiday-special
        - https://www.themoviedb.org/movie/732670-lego-star-wars-holiday-special
        - https://www.themoviedb.org/movie/12180-star-wars-the-clone-wars
    item_label: "Star Wars"
    collection_order: alpha
  Studio Ghibli:
    template: {name: tmdb}
    trakt_list_details: https://trakt.tv/users/draackje/lists/studio-ghibli-feature-films?sort=released,asc
    item_label: Ghibli
  Universal Monsters:
    template:
      name: tmdb
      collection:
        - https://www.themoviedb.org/collection/221539-dracula-universal-collection
        - https://www.themoviedb.org/collection/218406-frankenstein-universal-collection
        - https://www.themoviedb.org/collection/259401-the-invisible-man-collection
        - https://www.themoviedb.org/collection/221544-the-mummy-universal-collection
        - https://www.themoviedb.org/collection/259027-the-wolf-man-collection
        - https://www.themoviedb.org/collection/221537-creature-from-the-black-lagoon-collection
      movie:
        - https://www.themoviedb.org/movie/15855-phantom-of-the-opera
        - https://www.themoviedb.org/movie/27970-werewolf-of-london
        - https://www.themoviedb.org/movie/24106-the-black-cat
        - https://www.themoviedb.org/movie/17907-the-raven
        - https://www.themoviedb.org/movie/106296-the-monster-and-the-girl
        - https://www.themoviedb.org/movie/84719-man-made-monster
        - https://www.themoviedb.org/movie/45322-she-wolf-of-london
    summary: "Showcasing the most iconic monsters in motion picture history, including Dracula, Frankenstein's Monster, the Mummy, the Invisible Man, the Wolf Man, and more!"
  Vengeance Trilogy:
    template:
      name: tmdb
      movie:
        - https://www.themoviedb.org/movie/4689-mr-vengeance
        - https://www.themoviedb.org/movie/670-oldboy
        - https://www.themoviedb.org/movie/4550-sympathy-for-lady-vengeance


########################################
# Marvel Movies
########################################
  Black Widow:
    template: {name: tmdb, movie: 497698}
    minimum_items: 1
  Incredible Hulk:
    template: {name: tmdb, movie: 1724}
    item_label: MCU
    minimum_items: 1
  Spider-Man:
    template: {name: tmdb, collection: "556, 125574, 531241, 573436"}
    summary: "Films starring the Marvel Comics character Peter Parker, who gains spider-like abilities and learns that with great power comes great responsibility."
    item_label: Spider-Man

  MCU:
    build_collection: false
    template:
      name: tmdb
      collection:
        - https://www.themoviedb.org/collection/422834-ant-man-collection
        - https://www.themoviedb.org/collection/86311-the-avengers-collection
        - https://www.themoviedb.org/collection/529892-black-panther-collection
        - https://www.themoviedb.org/collection/131295-captain-america-collection
        - https://www.themoviedb.org/collection/623911-captain-marvel-collection
        - https://www.themoviedb.org/collection/618529-doctor-strange-collection
        - https://www.themoviedb.org/collection/1011336-eternals-collection
        - https://www.themoviedb.org/collection/284433-guardians-of-the-galaxy-collection
        - https://www.themoviedb.org/collection/131292-iron-man-collection
        - https://www.themoviedb.org/collection/912503-shang-chi-collection
        - https://www.themoviedb.org/collection/531241-spider-man-avengers-collection
        - https://www.themoviedb.org/collection/131296-thor-collection
      movie:
        - https://www.themoviedb.org/movie/497698-black-widow
        - https://www.themoviedb.org/movie/1724-the-incredible-hulk
        - https://www.themoviedb.org/movie/894205-werewolf-by-night
  MCEU:
    build_collection: false
    trakt_list:
      - https://trakt.tv/users/asterlea/lists/marvel?display=movie&sort=rank,asc
    item_label: MCEU

########################################
# DC Movies
########################################
  Batman:
    template: {name: tmdb, collection: 120794}
    name_mapping: "Batman (Burton)"
    sort_title: "Batman (Burton)"
    summary: "Tim Burton and Joel Schumacher's 4-film series of the icon DC Comics caped crusader."
    item_label: DC
  The Dark Knight:
    template: {name: tmdb, collection: 263}
    name_mapping: "Batman (Dark Knight)"
    sort_title: "Batman (Dark Knight)"
    summary: "Christopher Nolan's reboot of the Batman franchise, starring Christian Bale as the Dark Knight."
    item_label: DC

  DC Universe:
    trakt_list: 
      - https://trakt.tv/users/zosoleary/lists/dc-cinematic-universe
      - https://trakt.tv/users/malicekodi2/lists/dc
      - https://trakt.tv/lists/20583443
    smart_label:
      all:
        label: <<smart_label>>
      sort_by: release.asc
    minimum_items: 1
    item_label: DCU

########################################
# SMART COLLECTIONS
########################################

  "Tom's Watchlist":
    trakt_list: https://trakt.tv/users/tomhenrich/watchlist?sort=rank,asc
    smart_label:
      all:
        label: <<smart_label>>
        unplayed: true
    sort_title: "+Toms Watchlist"
    name_mapping: Toms Watchlist
    label: noshare
    minimum_items: 1

  "Sarah's Watchlist":
    trakt_list: 
      - https://trakt.tv/users/tomhenrich/lists/sarah-s-watchlist?sort=title,asc
      - https://trakt.tv/users/nursesawa/watchlist?sort=rank,asc
    smart_label:
      all:
        label: <<smart_label>>
        unplayed: true
      sort_by: title.asc
    sort_title: "+Sarahs Watchlist"
    name_mapping: Sarahs Watchlist
    label: noshare
    minimum_items: 1

  Non-English:
    smart_filter:
      any:
        audio_language.not: English
      sort_by: title.asc
    sort_title: "++Non-English"

  Hitchcock:
    plex_search:
      all:
        director: Alfred Hitchcock
    collection_order: release
    collection_mode: hide_items

  MonsterVerse:
    smart_filter:
      any:
        label: MonsterVerse
      sort_by: title.asc
    summary: The MonsterVerse is an American multimedia franchise and shared fictional universe featuring Godzilla, King Kong, and other Toho monster characters.

  Middle Earth:
    smart_label: title.asc
    tmdb_collection:
      - 119
      - 121938
    item_label.append: Middle Earth
    summary: "J.R.R. Tolkien's fantasy series following the adventures of Bilbo and Frodo Baggins." 

  "Star Trek: TOS":
    tmdb_collection_details: 151
    smart_label: title.asc
    sort_title: "Star Trek C1: TOS"
    item_label: Star Trek, Star Trek TOS
    name_mapping: Star Trek TOS
    collection_mode: hide

  "Star Trek: TNG":
    tmdb_collection_details: 115570
    smart_label: title.asc
    sort_title: "Star Trek C2: TNG"
    item_label: Star Trek, Star Trek TNG
    name_mapping: Star Trek TNG
    collection_mode: hide

  "Star Trek: Kelvin Timeline":
    tmdb_collection_details: 115575
    smart_label: title.asc
    sort_title: "Star Trek C3: Kelvin"
    item_label: Star Trek, Star Trek KEL
    name_mapping: Star Trek Kelvin
    collection_mode: hide

  Marvel Cinematic Universe:
    smart_filter:
      any:
        label: MCU
      sort_by: release.asc

  Marvel Extended Universe:
    smart_filter:
      any:
        label: MCEU
      sort_by: title.asc
    summary: Movies based on Marvel properties but not officially part of the Marvel Cinematic Universe.

  "Spider-Man (Raimi Trilogy)":
    tmdb_collection_details: 556
    name_mapping: "Spider-Man (Raimi)"
    smart_label: title.asc
    sort_title: "Spider-Man 2002"
    collection_mode: hide
  The Amazing Spider-Man:
    tmdb_collection_details: 125574
    name_mapping: Amazing Spider-Man
    smart_label: title.asc
    sort_title: "Spider-Man 2012"
    item_label: MCEU,Spider-Man
    collection_mode: hide
  "Spider-Verse":
    tmdb_collection_details: 573436
    smart_label: title.asc
    item_label: MCEU,Spider-Man
    collection_mode: hide
    minimum_items: 1
