templates:
  tmdb:
    optional:
      - collection
      - movie
    tmdb_collection_details: <<collection>>
    tmdb_movie: <<movie>>
    sync_mode: sync
    collection_order: release
    move_prefix: The,A
  tmdb_or_tag:
    optional:
      - collection
      - movie
      - tag
    tmdb_collection_details: <<collection>>
    tmdb_movie: <<movie>>
    plex_search:
      all:
        label: <<tag>>
    sync_mode: sync
    collection_order: release
    move_prefix: The,A
  tmdb_keyword:
    tmdb_keyword: <<keyword>>
    sync_mode: sync
    collection_order: release
    move_prefix: The,A

collections:
  Battlestar Galactica:
    template: {name: tmdb, collection: 91697}
    summary: "Follows the trials of the Colonial Fleet vessel Battlestar Galactica as it leads the last remaining humans on a search for Earth."
  Cloverfield:
    template: {name: tmdb, movie: "7191, 333371, 384521"}
  Eastrail 177:
    template: {name: tmdb, movie: "9741, 381288, 450465"}
    summary: "A superhero thriller and psychological horror film series involving the derailment of the fictitious Eastrail 177 train."
  Godzilla:
    template: {name: tmdb, collection: "374509, 374511, 374512, 535790, 535313", movie: "929, 315011"}
    collection_order: title.asc
    collection_mode: hide_items
    item_label: Godzilla
  I Am Legend:
    template: {name: tmdb, movie: "21159, 11234, 6479"}
    summary: "Films adapted from the novel I AM LEGEND by Richard Matheson."
  Kurosawa Samurai:
    template: {name: tmdb, movie: "548, 346, 3777, 1059, 11878, 11712, 11953, 11645"}
    summary: "Samurai films by the legendary Japanese director, Akira Kurosawa."
    item_label: Samurai
  The Manchurian Candidate:
    template: {name: tmdb, movie: "982, 14462"}
    name_mapping: Manchurian Candidate
    summary: "Film adaptations of Richard Condon's 1959 novel about an American who is brainwashed into being an unwitting assassin."
  Middle Earth:
    template: {name: tmdb, collection: "121938, 119"}
    item_label.append: Middle Earth
    summary: "J.R.R. Tolkien's fantasy series following the adventures of Bilbo and Frodo Baggins." 
  Serenity:
    template: {name: tmdb, movie: 16320}
    minimum_items: 1
    collection_mode: hide
  Star Trek:
    template: {name: tmdb, collection: "151, 115570, 115575"}
    item_label: Star Trek
    summary: "All films from the icon Star Trek franchise."
  Star Wars:
    template: {name: tmdb_or_tag, collection: 10, movie: "330459, 348350, 74849, 732670", tag: "Star Wars"}
    item_label: "Star Wars"
    collection_order: alpha
  Studio Ghibli:
    template: {name: tmdb}
    trakt_list_details: https://trakt.tv/users/draackje/lists/studio-ghibli-feature-films?sort=released,asc
    item_label: Ghibli
  Universal Monsters:
    template:
      name: tmdb
      collection:
        - 221539 # Dracula
        - 218406 # Frankenstein
        - 259401 # Invisible Man
        - 221544 # The Mummy
        - 259027 # Wolf-Man
        - 221537 # creature from the black lagoon
      movie:
        - 964 # the-phantom-of-the-opera
        - 27970 # werewolf-of-london
        - 24106 # the-black-cat
        - 17907 # the-raven
        - 106296 # monster and the girl
        - 84719 # man-made monsters
        - 45322 # she-wolf of london
    summary: "Showcasing the most iconic monsters in motion picture history, including Dracula, Frankenstein's Monster, the Mummy, the Invisible Man, the Wolf Man, and more!"
  Vengeance Trilogy:
    template: {name: tmdb, movie: "4689, 670, 4550"}
  MCU:
    build_collection: false
    template:
      name: tmdb
      collection:
        - 422834
        - 86311
        - 529892
        - 497698
        - 131295
        - 623911
        - 618529
        - 284433
        - 131292
        - 912503
        - 531241
        - 131296
      movie:
        - 1724    # Incredible Hulk
    item_label: MCU
  MCEU:
    build_collection: false
    template:
      name: tmdb
      collection:
        - 448150
        - 556
        - 125574
        - 573436
        - 556
        - 125574
        - 573436
        - 558216
        - 748
        - 453993
      movie:
        - 340102
    item_label: MCEU

########################################
# Marvel Movies
########################################
  Black Widow:
    template: {name: tmdb, movie: 497698}
    item_label: MCU
    minimum_items: 1
  Incredible Hulk:
    template: {name: tmdb, movie: 1724}
    item_label: MCU
    minimum_items: 1
  Spider-Man:
    template: {name: tmdb, collection: "556, 125574, 531241, 573436"}
    name_mapping: "Spider-Man"
    item_label: Spider-Man

########################################
# DC Movies
########################################
  Batman:
    template: {name: tmdb, collection: 120794}
    name_mapping: "Batman (Burton)"
    sort_title: "Batman (Burton)"
    summary: "Tim Burton and Joel Schumacher's 4-film series of the icon DC Comics caped crusader."
  The Dark Knight:
    template: {name: tmdb, collection: 263}
    name_mapping: "Batman (Dark Knight)"
    sort_title: "Batman (Dark Knight)"
    summary: "Christopher Nolan's reboot of the Batman franchise, starring Christian Bale as the Dark Knight."
