templates:
  tmdb:
    optional:
      - collection
      - movie
      - company
      - tmdb_summary
      - summary
      - order
    tmdb_collection_details: <<collection>>
    tmdb_movie: <<movie>>
    tmdb_company: <<company>>
    tmdb_summary: <<tmdb_summary>>
    summary: <<summary>>
    sync_mode: sync
    collection_order: release
    move_prefix: The,A

  Actor:
    plex_search:
      all:
        actor: tmdb
    tmdb_person: <<person>>
    sync_mode: sync

#
# CURATED COLLECTIONS
# Curated -- either not official TMDB collections, or specific combinations of movies
#

collections:

  Cloverfield:
    template:
      name: tmdb
      movie: 
        - 7191    # Cloverfield
        - 333371  # 10 Cloverfield Lane
        - 384521  # Cloverfield Paradox

  Cornetto Trilogy:
    template:
      name: tmdb
      movie:
        - 747     # Shaun of the Dead
        - 4638    # Hot Fuzz
        - 107985  # The World's End
    summary: The Three Flavours Cornetto trilogy is an anthology series of British comedies by Edgar Wright and Simon Pegg, starring Pegg and Nick Frost. 
    name_mapping: Cornetto
    minimum_items: 3
    collection_mode: show_items

  Cunk:
    template:
      name: tmdb
      movie:
        - 397385 # Cunk on Shakespeare
        - 431605 # Cunk on Christmas
    summary: Landmark mockumentary-maker Philomena Cunk guides us through history.

  Daredevil:
    template:
      name: tmdb
      movie:
        - 9480  # Daredevil
        - 9947  # Elektra

  Eastrail 177:
    template:
      name: tmdb
      movie: 
        - 9741    # Unbreakable
        - 381288  # Split
        - 450465  # Glass
    summary: "A superhero thriller and psychological horror film series involving the derailment of the fictitious Eastrail 177 train."
    collection_mode: show_items

  Galaxy Quest:
    template:
      name: tmdb
      movie:
        - 926 # Galaxy Quest
        - 637963 # Documentary
    collection_mode: hide

  Gamera:
    template:
      name: tmdb
      collection:
        - 161766  # Showa
        - 657313  # Heisei
      movie:
        - 60160   # Gamera the Brave
        - 664048  # 2015 short
    summary: "Gamera is a giant turtle Kaiju created by Daiei Motion Picture Company in 1965 to rival the success of Toho Studios' Godzilla franchise."

  I Am Legend:
    template:
      name: tmdb
      movie:
        - 21159 # The Last Man on Earth
        - 11234 # Omega Man
        - 6479  # I Am Legend
    summary: "Films adapted from the novel I AM LEGEND by Richard Matheson."

  Italian Job:
    template:
      name: tmdb
      movie:
        - 10536 # 1969
        - 9654  # 2003
    summary: "A team of criminals risk shifting allegiances and double-crosses to take on a daring heist."

  Jack Ryan:
    template:
      name: tmdb
      collection:
        - 192492  # Red October, Patriot Games, Clear and Present Danger
      movie:
        - 4614    # Sum of all Fears
        - 137094  # Shadow Recruit
    collection_mode: show_items

  King Kong:
    template:
      name: tmdb
      collection:
        - 135495  # 1930+
        - 135498  # 1976-1986
      movie:
        - 254     # 2005 Peter Jackson

  Kurosawa Samurai:
    template: {name: tmdb, movie: "548, 346, 3777, 1059, 11878, 11712, 11953, 11645"}
    summary: "Samurai films by the legendary Japanese director, Akira Kurosawa."
    item_label: Samurai

  Middle Earth:
    tmdb_collection:
      - 119     # LOTR
      - 121938  # Hobbit
    summary: "J.R.R. Tolkien's fantasy series following the adventures of Bilbo and Frodo Baggins."

  Serenity:
    template:
      name: tmdb
      movie: 16320
    minimum_items: 1
    collection_mode: hide

  Star Trek:
    tmdb_collection:
      - 151     # TOS
      - 115570  # TNG
      - 115575  # KEL
    item_label.append: Star Trek
    summary: "All films from the iconic Star Trek franchise."
    collection_order: release

  Studio Ghibli:
    template:
      name: tmdb
      movie:
        - 81  # Nausicaa
      company:
        - 10342
    collection_order: release

  Three Mothers:
    template:
      name: tmdb
      movie:
        - 11906 # Suspiria
        - 16395 # Inferno
        - 15206 # Mother of Tears
    summary: "Dario Argento's Italian supernatural horror saga that deals with a triumvirate of ancient witches whose powerful magic allows them to manipulate world events on a global scale."
    collection_mode: show_items

  Toho Kaiju:
    trakt_list: https://trakt.tv/users/tomhenrich/lists/toho-kaiju
    collection_order: release
    minimum_items: 1

  Vengeance Trilogy:
    template:
      name: tmdb
      movie:
        - 4689  # Sympathy for Mr Vengeance
        - 670   # Oldboy
        - 4550  # Lady Vengeance
    summary: "Park Chan-wook's Vengeance Trilogy proves revenge is a lot more than a dish best served cold."
    collection_mode: show_items

  Wizarding World:
    template:
      name: tmdb
      collection:
        - 1241    # Harry Potter
        - 435259  # Fantastic Beasts

  The Chocolate Factory:
    template:
      name: tmdb
      movie:
        - 252     # Willie Wonka (1971)
        - 118     # Charlie and the Chocolate Factory (2005)
        - 787699  # Wonka (2023)
    summary: "Come with me... and you'll be... in a world of pure imagination..."
    collection_mode: show_items
    name_mapping: Wonka


########################################
# Marvel/DC Movies
########################################
  Black Widow:
    template: {name: tmdb, movie: 497698}
    minimum_items: 1
    collection_mode: hide
  Incredible Hulk:
    template: {name: tmdb, movie: 1724}
    minimum_items: 1
    collection_mode: hide

  Marvel Cinematic Universe:
    tmdb_keyword: 180547
    smart_label:
      all:
        label: <<smart_label>>
      sort_by: release.asc

  Marvel Extended Universe:
    trakt_list:
      - https://trakt.tv/users/tomhenrich/lists/mceu
    smart_label:
      all:
        label: <<smart_label>>
      sort_by: release.asc
    summary: Movies based on Marvel properties but not officially part of the Marvel Cinematic Universe.

  DC Universe:
    trakt_list: 
      - https://trakt.tv/users/tomhenrich/lists/dc-universe
    smart_label:
      all:
        label: <<smart_label>>
      sort_by: release.asc
    minimum_items: 1


########################################
# OTHER
########################################

  "Sarah's Watchlist":
    trakt_list: 
      - https://trakt.tv/users/tomhenrich/lists/sarah-s-watchlist?display=movie
      - https://trakt.tv/users/nursesawa/watchlist?display=movie
    smart_label:
      all:
        label: <<smart_label>>
        unplayed: true
      sort_by: title.asc
    sort_title: "!Sarahs Watchlist"
    name_mapping: Sarahs Watchlist
    label: noshare
    minimum_items: 1

  "Tom's Watchlist":
    trakt_list: https://trakt.tv/users/tomhenrich/watchlist?display=movie
    smart_label:
      all:
        label: <<smart_label>>
        unplayed: true
      sort_by: title.asc
    sort_title: "!Toms Watchlist"
    name_mapping: Toms Watchlist
    label: noshare
    minimum_items: 1

  Unwatched:
    smart_filter:
      all:
        unplayed: true
      sort_by: duration.asc
    sort_title: "!Unwatched"
    collection_filtering: user

  Non-English:
    smart_filter:
      any:
        audio_language.not: English
      sort_by: title.asc
    sort_title: "zzzNon-English"
    summary: "You're gonna need to be okay with subtitles."

  Best of Robin Williams:
    sort_title: Robin Williams
    smart_filter:
      all:
        actor: tmdb
        audience_rating.gte: 7
      sort_by: release.asc
    tmdb_person: 2157
    summary: Films starring Robin Williams that received a 70% or higher score from audiences.

  Hitchcock:
    smart_filter:
      all:
        director: Alfred Hitchcock
      sort_by: release.asc

  Laika Studios:
    smart_filter:
      all:
        studio.begins: Laika
      sort_by: release.asc

  MonsterVerse:
    smart_filter:
      all:
        label: MonsterVerse
      sort_by: release.asc

  Stephen King:
    trakt_list: https://trakt.tv/users/hawque/lists/stephen-king?display=movie
    smart_label:
      all:
        label: <<smart_label>>
      sort_by: release.asc
    summary: "Movies adapted from Stephen King novels."

  Universal Classic Monsters:
    trakt_list: https://trakt.tv/users/tomhenrich/lists/universal-monsters?sort=released,desc
    smart_label:
      all:
        label: <<smart_label>>
      sort_by: release.asc
    summary: "Showcasing the most iconic monsters in motion picture history, including Dracula, Frankenstein's Monster, the Mummy, the Invisible Man, the Wolf Man, and more!"


  Choice Fatigue:
    smart_filter:
      limit: 5
      all:
        unplayed: true
        audio_language: English
        release: 3650
        audience_rating.gte: 6
        genre.not:
          - Horror
          - Short
      sort_by: random
    sort_title: "!Choice Fatigue"
    collection_filtering: user
    summary: "Can't decide what to watch? Here are a few popular selections released in the last decade."
