templates:
  tmdb:
    optional:
      - collection
      - movie
      - tmdb_summary
      - summary
      - order
    tmdb_collection_details: <<collection>>
    tmdb_movie: <<movie>>
    tmdb_summary: <<tmdb_summary>>
    summary: <<summary>>
    sync_mode: sync
    collection_order: release
    move_prefix: The,A

  tmdb_or_tag:
    optional:
      - collection
      - movie
      - tag
      - tmdb_summary
      - summary
      - order
    tmdb_collection_details: <<collection>>
    tmdb_movie: <<movie>>
    tmdb_summary: <<tmdb_summary>>
    plex_search:
      all:
        label: <<tag>>
    sync_mode: sync
    collection_order: <<order>>
    move_prefix: The,A
  tmdb_keyword:
    tmdb_keyword: <<keyword>>
    sync_mode: sync
    collection_order: release
    move_prefix: The,A

  Actor:
    plex_search:
      all:
        actor: tmdb
    tmdb_person: <<person>>
    sync_mode: sync

#
# CURATED COLLECTIONS
# Curated -- either not official TMDB collections, or specific combinations of movies
#
collections:
  Cloverfield:
    template:
      name: tmdb
      movie: 
        - 7191    # Cloverfield
        - 333371  # 10 Cloverfield Lane
        - 384521  # Cloverfield Paradox
  Eastrail 177:
    template:
      name: tmdb
      movie: 
        - 9741    # Unbreakable
        - 381288  # Split
        - 450465  # Glass
    summary: "A superhero thriller and psychological horror film series involving the derailment of the fictitious Eastrail 177 train."
  I Am Legend:
    template:
      name: tmdb
      collection:
        - 945984 # I am Legend (Will Smith)
      movie:
        - 21159 # The Last Man on Earth
        - 11234 # Omega Man
        - 6479  # I Am Legend
    summary: "Films adapted from the novel I AM LEGEND by Richard Matheson."
  Kurosawa Samurai:
    template: {name: tmdb, movie: "548, 346, 3777, 1059, 11878, 11712, 11953, 11645"}
    summary: "Samurai films by the legendary Japanese director, Akira Kurosawa."
    item_label: Samurai
  Serenity:
    template:
      name: tmdb
      movie: 16320
    minimum_items: 1
    collection_mode: hide
  Universal Monsters:
    template:
      name: tmdb
      collection:
        - 221539
        - 218406
        - 259401
        - 221544
        - 259027
        - 221537
      movie:
        - 15855
        - 27970
        - 24106
        - 17907
        - 106296
        - 84719
        - 45322
    summary: "Showcasing the most iconic monsters in motion picture history, including Dracula, Frankenstein's Monster, the Mummy, the Invisible Man, the Wolf Man, and more!"
  Vengeance:
    template:
      name: tmdb
      movie: 
        - 4689  # Sympathy for Mr Vengeance
        - 670   # Oldboy
        - 4550  # Lady Vengeance
    summary: "Park Chan-wook's Vengeance Trilogy proves revenge is a lot more than a dish best served cold."
    collection_order: release
    name_mapping: "Vengeance Trilogy"

########################################
# TRAKT-BASED COLLECTIONS
########################################

  Godzilla:
    trakt_list: https://trakt.tv/users/tomhenrich/lists/godzilla?sort=rank,asc
    summary: "The King of the Monsters."
    collection_order: custom
    item_label: Godzilla
    sort_title: "Godzilla +"
    build_collection: false

  Studio Ghibli:
    trakt_list_details: https://trakt.tv/users/tomhenrich/lists/ghibli
    collection_order: release
    item_label: Ghibli

  Toho Kaiju:
    trakt_list: https://trakt.tv/users/tomhenrich/lists/toho-kaiju
    collection_order: release
    minimum_items: 1

########################################
# Marvel/DC Movies
########################################
  Black Widow:
    template: {name: tmdb, movie: 497698}
    item_label: MCU
    minimum_items: 1
  Incredible Hulk:
    template: {name: tmdb, movie: 1724}
    item_label: MCU
    minimum_items: 1

  Marvel Cinematic Universe:
    trakt_list: https://trakt.tv/users/asterlea/lists/mcu?display=movie&sort=release,asc
    smart_label:
      all:
        label: <<smart_label>>
      sort_by: release.asc
    item_label: MCU

  Marvel Extended Universe:
    trakt_list: https://trakt.tv/users/asterlea/lists/marvel?display=movie&sort=release,asc
    smart_label:
      all:
        label: <<smart_label>>
      sort_by: release.asc
    summary: Movies based on Marvel properties but not officially part of the Marvel Cinematic Universe.
    item_label: MCEU

  DC Universe:
    trakt_list: 
      - https://trakt.tv/users/zosoleary/lists/dc-cinematic-universe
      - https://trakt.tv/users/malicekodi2/lists/dc
      - https://trakt.tv/lists/20583443
    smart_label:
      all:
        label: <<smart_label>>
      sort_by: release.asc
    minimum_items: 1
    item_label: DCU

########################################
# OTHER
########################################

  "Tom's Watchlist":
    trakt_list: https://trakt.tv/users/tomhenrich/watchlist?sort=rank,asc
    smart_label:
      all:
        label: <<smart_label>>
        unplayed: true
    sort_title: "+Toms Watchlist"
    name_mapping: Toms Watchlist
    label: noshare
    minimum_items: 1

  "Sarah's Watchlist":
    trakt_list: 
      - https://trakt.tv/users/tomhenrich/lists/sarah-s-watchlist?sort=title,asc
      - https://trakt.tv/users/nursesawa/watchlist?sort=rank,asc
    smart_label:
      all:
        label: <<smart_label>>
        unplayed: true
      sort_by: title.asc
    sort_title: "+Sarahs Watchlist"
    name_mapping: Sarahs Watchlist
    label: noshare
    minimum_items: 1

  Non-English:
    smart_filter:
      any:
        audio_language.not: English
      sort_by: title.asc
    sort_title: "++Non-English"

  Hitchcock:
    plex_search:
      all:
        director: Alfred Hitchcock
    collection_order: release
    collection_mode: hide_items

  Middle Earth:
    smart_label: title.asc
    tmdb_collection:
      - 119
      - 121938
    item_label.append: Middle Earth
    summary: "J.R.R. Tolkien's fantasy series following the adventures of Bilbo and Frodo Baggins." 

  MonsterVerse:
    smart_filter:
      any:
        label: MonsterVerse
      sort_by: title.asc
    summary: The MonsterVerse is an American multimedia franchise and shared fictional universe featuring Godzilla, King Kong, and other Toho monster characters.

  Best of Robin Williams:
    sort_title: Robin Williams
    smart_filter:
      all:
        actor: tmdb
        audience_rating.gte: 7
    tmdb_person: 2157
    summary: Films starring Robin Williams that received a 70% or higher score from audiences.

  Star Trek:
    smart_filter:
      any:
        label: Star Trek
      sort_by: release.asc
    summary: "All films from the iconic Star Trek franchise."
