metadata:
  The Matrix:
    match:
      mapping_id: 603
    summary: "Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth."
  
# ####################
# STAR WARS
# ####################

  The Phantom Menace:
    match:
      mapping_id: 1893
    title: "Star Wars I: The Phantom Menace"
    sort_title: Star Wars 1
  Attack of the Clones:
    match:
      mapping_id: 1894
    title: "Star Wars II: Attack of the Clones"
    sort_title: Star Wars 2
  Revenge of the Sith:
    match:
      mapping_id: 1895
    title: "Star Wars III: Revenge of the Sith"
    sort_title: Star Wars 3
  A New Hope:
    match:
      mapping_id: 11
    title: "Star Wars IV: A New Hope"
    sort_title: Star Wars 4
  The Empire Strikes Back:
    match:
      mapping_id: 1891
    title: "Star Wars V: The Empire Strikes Back"
    sort_title: Star Wars 5
  Return of the Jedi:
    match:
      mapping_id: 1892
    title: "Star Wars VI: Return of the Jedi"
    sort_title: Star Wars 6
  The Force Awakens:
    match:
      mapping_id: 140607
    title: "Star Wars VII: The Force Awakens"
    sort_title: Star Wars 7
  The Last Jedi:
    match:
      mapping_id: 181808
    title: "Star Wars VIII: The Last Jedi"
    sort_title: Star Wars 8
    label: Star Wars
  The Rise of Skywalker:
    match:
      mapping_id: 181812
    title: "Star Wars IX: The Rise of Skywalker"
    sort_title: Star Wars 9
  "Solo: A Star Wars Story":
    match:
      mapping_id: 348350
    sort_title: Star Wars 3.5
  "Rogue One: A Star Wars Story":
    match:
      mapping_id: 330459
    sort_title: Star Wars 3.9
  The LEGO Star Wars Holiday Special:
    match:
      mapping_id: 732670
    sort_title: Star Wars 900
  A Disturbance in the Force:
    match:
      mapping_id: 765673
    sort_title: Star Wars 999


# ####################
# STAR TREK
# ####################

  "Star Trek: The Motion Picture":
    sort_title: Star Trek 1
  "Star Trek II: The Wrath of Khan":
    sort_title: Star Trek 2
  "Star Trek III: The Search for Spock":
    sort_title: Star Trek 3
  "Star Trek IV: The Voyage Home":
    sort_title: Star Trek 4
  "Star Trek V: The Final Frontier":
    sort_title: Star Trek 5
  "Star Trek VI: The Undiscovered Country":
    sort_title: Star Trek 6
  
  "Star Trek: Generations":
    sort_title: Star Trek 7
  "Star Trek: First Contact":
    sort_title: Star Trek 8
  "Star Trek: Insurrection":
    sort_title: Star Trek 9
  "Star Trek: Nemesis":
    sort_title: Star Trek 10

  "Star Trek":
    match:
      year: 2009
    sort_title: Star Trek 2009
  "Star Trek Into Darkness":
    sort_title: Star Trek 2013
  "Star Trek Beyond":
    sort_title: Star Trek 2016
  

# ####################
# MIDDLE-EARTH
# ####################

  The Fellowship of the Ring:
    match:
      mapping_id: 120
    original_title: "The Lord of the Rings: The Fellowship of the Ring"
    summary: "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle Earth from the Dark Lord Sauron."
    sort_title: LOTR 1
  The Two Towers:
    match:
      mapping_id: 121
    original_title: "The Lord of the Rings: The Two Towers"
    summary: "While Frodo and Sam edge closer to Mordor with the help of Gollum, the divided fellowship makes a stand against Sauron's new ally, Saruman."
    sort_title: LOTR 2
  The Return of the King:
    match:
      mapping_id: 122
    original_title: "The Lord of the Rings: The Return of the King"
    summary: "Gandalf and Aragorn lead the world of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring."
    sort_title: LOTR 3
  "The Hobbit: An Unexpected Journey":
    match:
      mapping_id: 49051
    sort_title: Hobbit 1
  "The Hobbit: The Desolation of Smaug":
    match:
      mapping_id: 57158
    sort_title: Hobbit 2
  "The Hobbit: The Battle of the Five Armies":
    match:
      mapping_id: 122917
    sort_title: Hobbit 3


# ####################
# GODZILLA
# ####################

  Gojira: #-- Godzilla
    title: Godzilla
    match:
      mapping_id: 1678
      year: 1954
    sort_title: Godzilla Era 1 - 1
  1679: #-- Godzilla Raids Again
    title: Godzilla Raids Again
    sort_title: Godzilla Era 1 - 2
  1680: #-- King Kong vs. Godzilla
    sort_title: Godzilla Era 1 - 3
  1682: #-- Mothra vs. Godzilla
    sort_title: Godzilla Era 1 - 4
  15766: #-- Ghidorah, the Three-Headed Monster
    sort_title: Godzilla Era 1 - 5
  19545: #-- Invasion of Astro-Monster
    sort_title: Godzilla Era 1 - 6
  3115: #-- Ebirah, Horror of the Deep
    sort_title: Godzilla Era 1 - 7
  18627: #-- Son of Godzilla
    sort_title: Godzilla Era 1 - 8
  3107: #-- Destroy All Monsters
    sort_title: Godzilla Era 1 - 9
  39462: #-- All Monsters Attack
    sort_title: Godzilla Era 1 - 10
  39464: #-- Godzilla vs. Hedorah
    sort_title: Godzilla Era 1 - 11
  19336: #-- Godzilla vs. Gigan
    sort_title: Godzilla Era 1 - 12
  39264: #-- Godzilla vs. Megalon
    sort_title: Godzilla Era 1 - 13
  38582: #-- Godzilla vs. Mechagodzilla
    sort_title: Godzilla Era 1 - 14
  19333: #-- Terror of Mechagodzilla
    sort_title: Godzilla Era 1 - 15

  18983: #-- Godzilla KOTM (US)
    sort_title: Godzilla Era 1 - 1956
#  329237: #-- Gigantis the Fire Monster (US)
#    sort_title: Godzilla Era 1 - 1959
  686487: #-- King Kong vs Godzilla (US)
    sort_title: Godzilla Era 1 - 1963

  421467: #-- Return of Godzilla
    sort_title: Godzilla Era 2 - 1
  18289: #-- Godzilla vs. Biollante
    sort_title: Godzilla Era 2 - 2
    summary: Concerned over Godzilla's possible return after the previous attack, the Japanese government uses his cells to create a new bioweapon, Anti-Nuclear Energy Bacteria. They enlist geneticist Genshiro Shiragami, whose experiments result in a new monstrous mutation.
  36679: #-- Godzilla vs. King Ghidorah
    sort_title: Godzilla Era 2 - 3
  39465: #-- Godzilla vs. Mothra
    sort_title: Godzilla Era 2 - 4
  6593: #-- Godzilla vs. MechaGodzilla II
    sort_title: Godzilla Era 2 - 5
  39466: #-- Godzilla vs. SpaceGodzilla
    sort_title: Godzilla Era 2 - 6
    summary: "Godzilla is threatened by two new forces: Mogera (another UN-built machine), and SpaceGodzilla - an extraterrestrial beast spawned when Godzilla's cells were carried into space by Mothra and warped by a black hole."
  12561: #-- Godzilla vs. Destoroyah
    sort_title: Godzilla Era 2 - 7

  10643: #-- Godzilla 2000
    title: "Godzilla 2000: Millennium"
    sort_title: Godzilla Era3 - 1
    summary: Godzilla is a literal force of nature to Japan. Scientists find a sixty-million-year-old UFO deep in the Japan Trench. As they attempt to raise the UFO to study it, it takes off into the sky on its own, searching for genetic information that only Godzilla possesses.
  39468: #-- Godzilla vs. Megaguirus
    sort_title: Godzilla Era3 - 2
    summary: In an alternate timeline, the original Godzilla was never defeated and now repeatedly re-emerges to feed on Japan's energy sources. A new inter-dimensional weapon called the Dimension Tide is created to eliminate Godzilla... however, the new weapon might also serve as a gateway to something far more sinister.
  36243: #-- GMK
    sort_title: Godzilla Era3 - 3
    title: "Giant Monsters All-Out Attack"
    summary: Ignoring all prior movies except the original, Godzilla is a distant memory for Japan when the destruction of a US submarine raises alarms. The ancient guardian monsters must rise to protect Japan against the vengeful spirits within Godzilla that seek revenge for the suffering Japan inflicted in the Pacific conflict.
  12636: #-- Godzilla Against MechaGodzilla
    sort_title: Godzilla Era3 - 4
    summary: When a new Godzilla emerges, a cyborg version named Kiryu is constructed from the remains of the 1954 monster. The machine is discovered to harbor the restless soul of the original Godzilla as JSDF pilot Akane Yashiro must learn to find value in her own life as well.
  39469: #-- Godzilla Tokyo SOS
    sort_title: Godzilla Era3 - 5
    summary: In this sequel to "Godzilla Against MechaGodzilla", Mothra and her fairies return to Japan to warn mankind that Kiryu must be returned to the sea, for the dead must not be disturbed. However, Godzilla has survived to menace Japan, leaving MechaGodzilla as the nation's only defense.
  15767: #-- Godzilla Final Wars
    sort_title: Godzilla Era3 - 6
    summary: "Ignoring all prior movies from this era, humanity finally imprisons Godzilla in the South Pole. All is peaceful until monsters emerge to lay waste to Earth's cities. A race of benevolent aliens known as Xiliens arrive to help, but not all is what it seems with these bizarre visitors. If humanity wishes to survive, they must reluctantly resurrect their most hated enemy: Godzilla."

  929: #-- Godzilla 1998
    title: Godzilla
    sort_title: Godzilla Era 98

# ####################

  The Crimes of Grindelwald:
    match:
      mapping_id: 338952
    alt_title: "Fantastic Beasts: The Crimes of Grindelwald"
  The Secrets of Dumbledore:
    match:
      mapping_id: 338953
    alt_title: "Fantastic Beasts: The Secrets of Dumbledore"

# ####################

  Pitch Black:
    sort_title: Chronicles of Riddick 1
  Dark Fury:
    match:
      mapping_id: 2791
    alt_title: "The Chronicles of Riddick: Dark Fury"
    sort_title: Chronicles of Riddick 1.5
  The Chronicles of Riddick:
    match:
      mapping_id: 2789
    sort_title: Chronicles of Riddick 2
    edition: "Director's Cut"
    content_rating: Unrated
  Riddick:
    match:
      mapping_id: 87421
    sort_title: Chronicles of Riddick 3

# ####################
# JURASSIC PARK
# ####################

  Jurassic Park:
    sort_title: Jurassic Park 1
  "The Lost World: Jurassic Park": 
    sort_title: Jurassic Park 2
  Jurassic Park III: 
    sort_title: Jurassic Park 3
  Jurassic World: 
    sort_title: Jurassic World 1
  "Jurassic World: Fallen Kingdom": 
    sort_title: Jurassic World 2
  Battle at Big Rock: 
    sort_title: Jurassic World 2.5
  Jurassic World Dominion: 
    sort_title: Jurassic World 3


# ####################
# DC
# ####################

  Superman Returns:
    sort_title: Superman 5

  Batman:
    sort_title: Batman 1
  Batman Returns:
    sort_title: Batman 2
    summary: "While Batman deals with a deformed man calling himself the Penguin, an employee of a corrupt businessman transforms into the Catwoman."
  Batman Forever:
    sort_title: Batman 3
    summary: "Batman must battle a disfigured district attorney and a disgruntled former employee with help from an amorous psychologist and a young circus acrobat."
  "Batman & Robin":
    sort_title: Batman 4
    summary: "Batman and Robin try to keep their relationship together even as they must stop Mr. Freeze and Poison Ivy from freezing Gotham City."

  Batman Begins:
    match:
      year: 2005
    sort_title: Dark Knight 1
  The Dark Knight:
    match:
      year: 2008
    sort_title: Dark Knight 2
  The Dark Knight Rises:
    match:
      year: 2012
    sort_title: Dark Knight 3

# ####################

  "Gamera, the Giant Monster":
    match:
      year: 1965
    sort_title: Gamera 1
  Gamera vs. Barugon:
    match:
      year: 1966
    sort_title: Gamera 2
  Gamera vs. Gyaos:
    match:
      year: 1967
    sort_title: Gamera 3
  Gamera vs. Viras:
    match:
      year: 1968
    sort_title: Gamera 4
  Gamera vs. Guiron:
    match:
      year: 1969
    sort_title: Gamera 5
  Gamera vs. Jiger:
    match:
      year: 1970
    sort_title: Gamera 6
  Gamera vs. Zigra:
    match:
      year: 1971
    sort_title: Gamera 7
  "Gamera: Super Monster":
    match:
      year: 1980
    sort_title: Gamera 8
  Gamera the Brave:
    match:
      year: 2006
    sort_title: Gamera 9

  "Gamera: Guardian of the Universe":
    match:
      year: 1995
    summary: "A monstrous new species of bird appears just as a teenage girl is gifted an amulet that was found on a mysterious atoll. As the creatures begin to attack, an ancient guardian emerges."
    sort_title: Gamera Heisei 1
  "Gamera 2: Attack of Legion":
    match:
      year: 1996
    summary: "A meteor lands in Japan and unleashes hundreds of insect-like 'Legion' creatures. Gamera shows up to deal with the ever-evolving adversary, but the battle may result in him losing his bond with humanity."
    sort_title: Gamera Heisei 2
  "Gamera 3: Revenge of Iris":
    match:
      year: 1999
    summary: "Gamera's ties to humanity have been severed as the monstrous Gyaos re-emerge. An orphaned girl named Ayana discovers a new creature she names Iris, and seeks revenge on Gamera for the death of her family."
    sort_title: Gamera Heisei 3

  Gamera:
    match:
      year: 2015
    sort_title: Gamera 2015
    edition: Short Film

# ####################
# MARVEL
# ####################

  24428:
    sort_title: Avengers 1
  99861:
    sort_title: Avengers 2
  299536:
    sort_title: Avengers 3
  299534:
    sort_title: Avengers 4

  1771:
    sort_title: Captain America 1
  100402:
    sort_title: Captain America 2
  271110:
    sort_title: Captain America 3

  76338:
    sort_title: Thor 2
  284053:
    sort_title: Thor 3
  616037:
    sort_title: Thor 4

  "Spider-Man: Homecoming":
    match:
      mapping_id: 315635
    sort_title: Spider-Man Avengers 1
  "Spider-Man: Far From Home":
    match:
      mapping_id: 429617
    sort_title: Spider-Man Avengers 2
  "Spider-Man: No Way Home":
    match:
      mapping_id: 634649
    sort_title: Spider-Man Avengers 3

  36658:
    title: "X2: X-Men United"
    sort_title: X-Men 2
  36668:
    sort_title: X-Men 3
  "X-Men: First Class":
    match:
      mapping_id: 49538
    sort_title: X-Men 4
  "X-Men: Days of Future Past":
    match:
      mapping_id: 127585
    sort_title: X-Men 5
  "X-Men: Apocalypse":
    match:
      mapping_id: 246655
    sort_title: X-Men 6

  324857:
    sort_title: Spider-Verse 1
  569094:
    sort_title: Spider-Verse 2

  36647:
    sort_title: Blade 1
  36586:
    sort_title: Blade 2
  36648:
    sort_title: Blade 3

# ####################

  Princess Mononoke:
    match:
      mapping_id: 128
    year: 1997
    summary: "Ashitaka is cursed by a demonized boar god and must journey to the west to find a cure. Along the way, he meets San, a human woman fighting to protect the forest, and Lady Eboshi, who is trying to destroy it."

  "Battlestar Galactica: Razor":
    match:
      mapping_id: 69315
    sort_title: Battlestar Reboot 1
  "Battlestar Galactica: The Plan":
    match:
      mapping_id: 105077
    sort_title: Battlestar Reboot 2
  "Battlestar Galactica: Blood & Chrome":
    match:
      mapping_id: 257368
    sort_title: Battlestar Reboot 3

  10 Cloverfield Lane:
    sort_title: Cloverfield 2
  The Cloverfield Paradox:
    sort_title: Cloverfield 3
  
  Ghostbusters:
    match:
      year: 1984
    sort_title: Ghostbusters 1984
  Ghostbusters2016:
    match:
      year: 2016
      title: Ghostbusters
    title: Ghostbusters
    sort_title: Ghostbusters 2016
  "Ghostbusters: Afterlife":
    sort_title: Ghostbusters 2021

  9799:
    sort_title: Fast and Furious 1
  584:
    sort_title: Fast and Furious 2
  9615:
    sort_title: Fast and Furious 3
  13804:
    sort_title: Fast and Furious 4
  51497:
    sort_title: Fast and Furious 5
  82992:
    sort_title: Fast and Furious 6
  168259:
    sort_title: Fast and Furious 7
  337339:
    sort_title: Fast and Furious 8
  385128:
    sort_title: Fast and Furious 9
  385687:
    sort_title: Fast and Furious 10

  348:
    sort_title: Alien 1
  679:
    sort_title: Alien 2
  8077:
    sort_title: Alien 3
  8078:
    sort_title: Alien 4
  Prometheus:
    match:
      year: 2012
    sort_title: Alien 5
  "Alien: Covenant":
    match:
      year: 2017
    sort_title: Alien 6

  395:
    sort_title: Alien vs Predator 1

  1685:
    sort_title: Planet of the Apes 2
  1687:
    sort_title: Planet of the Apes 3
  1688:
    sort_title: Planet of the Apes 4
  1705:
    sort_title: Planet of the Apes 5

  61791:
    sort_title: Planet of the Apes Reboot 1
  119450:
    sort_title: Planet of the Apes Reboot 2
  281338:
    sort_title: Planet of the Apes Reboot 3

  2501:
    sort_title: Bourne 1
  2502:
    sort_title: Bourne 2
  2503:
    sort_title: Bourne 3
  49040:
    sort_title: Bourne 4
  324668:
    sort_title: Bourne 5

  1572:
    sort_title: Die Hard 3
  1571:
    sort_title: Die Hard 4

  "Transformers: Revenge of the Fallen":
    sort_title: Transformers 2
  "Transformers: Dark of the Moon":
    sort_title: Transformers 3
  "Transformers: Age of Extinction":
    sort_title: Transformers 4
  "Transformers: The Last Knight":
    sort_title: Transformers 5

  Finding Dory:
    sort_title: Finding Nemo 2

  Raiders of the Lost Ark:
    sort_title: Indiana Jones 1
    title: Indiana Jones and the Raiders of the Lost Ark
  Indiana Jones and the Temple of Doom:
    sort_title: Indiana Jones 2
  Indiana Jones and the Last Crusade:
    sort_title: Indiana Jones 3
  Indiana Jones and the Kingdom of the Crystal Skull:
    sort_title: Indiana Jones 4
  Indiana Jones and the Dial of Destiny:
    sort_title: Indiana Jones 5

  "Jumanji: Welcome to the Jungle":
    sort_title: Jumanji 2
  "Jumanji: The Next Level":
    sort_title: Jumanji 3

  Men in Black II:
    sort_title: Men in Black 2
  "Men in Black: International":
    sort_title: Men in Black 4

  The Mummy:
    match:
      year: 1999
    sort_title: Mummy 1
  The Mummy Returns:
    match:
      year: 2001
    sort_title: Mummy 2
  "The Mummy: Tomb of the Dragon Emperor":
    match:
      year: 2008
    sort_title: Mummy 3

  Terminator Salvation:
    sort_title: Terminator 4
  Terminator Genisys:
    sort_title: Terminator 5
  "Terminator: Dark Fate":
    sort_title: Terminator 6

  "Resident Evil: Apocalypse":
    sort_title: Resident Evil 2
  "Resident Evil: Extinction":
    sort_title: Resident Evil 3
  "Resident Evil: Afterlife":
    sort_title: Resident Evil 4

  Dracula:
    match:
      year: 1931
    sort_title: Dracula Universal 1
  "Dracula's Daughter":
    match:
      year: 1936
    sort_title: Dracula Universal 2
  Son of Dracula:
    match:
      year: 1943
    sort_title: Dracula Universal 3
  House of Dracula:
    match:
      year: 1945
    sort_title: Dracula Universal 4

  Frankenstein:
    match:
      year: 1931
    sort_title: Frankenstein Universal 1
  Bride of Frankenstein:
    match:
      year: 1935
    sort_title: Frankenstein Universal 2
  Son of Frankenstein:
    match:
      year: 1939
    sort_title: Frankenstein Universal 3
  The Ghost of Frankenstein:
    match:
      year: 1942
    sort_title: Frankenstein Universal 4
  House of Frankenstein:
    match:
      year: 1944
    sort_title: Frankenstein Universal 5

  The Mummy 1932:
    match:
      title: The Mummy
      year: 1932
    title: The Mummy
    sort_title: Mummy Universal 1
  "The Mummy's Hand":
    match:
      year: 1940
    sort_title: Mummy Universal 2
  "The Mummy's Tomb":
    match:
      year: 1942
    sort_title: Mummy Universal 3
  "The Mummy's Ghost":
    match:
      year: 1944
    sort_title: Mummy Universal 4
  "The Mummy's Curse":
    match:
      year: 1944
    sort_title: Mummy Universal 5


  Before Sunrise:
    match:
      year: 1995
    sort_title: Before 1
  Before Sunset:
    match:
      year: 2004
    sort_title: Before 2
  Before Midnight:
    match:
      year: 2013
    sort_title: Before 3
