metadata:
  The Matrix:
    match:
      mapping_id: 603
    summary: "Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth."

  A Star Is Born:
    sort_title: A Star Is Born
  
# ####################
# STAR WARS
# ####################

  The Phantom Menace:
    match:
      mapping_id: 1893
    title: "Star Wars I: The Phantom Menace"
    sort_title: Star Wars 1
  Attack of the Clones:
    match:
      mapping_id: 1894
    title: "Star Wars II: Attack of the Clones"
    sort_title: Star Wars 2
  Revenge of the Sith:
    match:
      mapping_id: 1895
    title: "Star Wars III: Revenge of the Sith"
    sort_title: Star Wars 3
  A New Hope:
    match:
      mapping_id: 11
    title: "Star Wars IV: A New Hope"
    sort_title: Star Wars 4
  The Empire Strikes Back:
    match:
      mapping_id: 1891
    title: "Star Wars V: The Empire Strikes Back"
    sort_title: Star Wars 5
  Return of the Jedi:
    match:
      mapping_id: 1892
    title: "Star Wars VI: Return of the Jedi"
    sort_title: Star Wars 6
  The Force Awakens:
    match:
      mapping_id: 140607
    title: "Star Wars VII: The Force Awakens"
    sort_title: Star Wars 7
  The Last Jedi:
    match:
      mapping_id: 181808
    title: "Star Wars VIII: The Last Jedi"
    sort_title: Star Wars 8
  The Rise of Skywalker:
    match:
      mapping_id: 181812
    title: "Star Wars IX: The Rise of Skywalker"
    sort_title: Star Wars 9
  "Solo: A Star Wars Story":
    match:
      mapping_id: 348350
    sort_title: Star Wars 3.5
  "Rogue One: A Star Wars Story":
    match:
      mapping_id: 330459
    sort_title: Star Wars 3.9
  The LEGO Star Wars Holiday Special:
    match:
      mapping_id: 732670
    sort_title: Star Wars 900
  A Disturbance in the Force:
    match:
      mapping_id: 765673
    sort_title: Star Wars 999


# ####################
# STAR TREK
# ####################

  "Star Trek: The Motion Picture":
    sort_title: Star Trek 1
  "Star Trek II: The Wrath of Khan":
    sort_title: Star Trek 2
  "Star Trek III: The Search for Spock":
    sort_title: Star Trek 3
  "Star Trek IV: The Voyage Home":
    sort_title: Star Trek 4
  "Star Trek V: The Final Frontier":
    sort_title: Star Trek 5
  "Star Trek VI: The Undiscovered Country":
    sort_title: Star Trek 6
  
  "Star Trek: Generations":
    sort_title: Star Trek 7
  "Star Trek: First Contact":
    sort_title: Star Trek 8
  "Star Trek: Insurrection":
    sort_title: Star Trek 9
  "Star Trek: Nemesis":
    sort_title: Star Trek 10

  Star Trek:
    match:
      year: 2009
    sort_title: Star Trek 2009
  Star Trek Into Darkness:
    sort_title: Star Trek 2013
  Star Trek Beyond:
    sort_title: Star Trek 2016
  

# ####################
# MIDDLE-EARTH
# ####################

  The Fellowship of the Ring:
    match:
      mapping_id: 120
    original_title: "The Lord of the Rings: The Fellowship of the Ring"
    summary: "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle Earth from the Dark Lord Sauron."
    sort_title: Lord of the Rings 1
  The Two Towers:
    match:
      mapping_id: 121
    original_title: "The Lord of the Rings: The Two Towers"
    summary: "While Frodo and Sam edge closer to Mordor with the help of Gollum, the divided fellowship makes a stand against Sauron's new ally, Saruman."
    sort_title: Lord of the Rings 2
  The Return of the King:
    match:
      mapping_id: 122
    original_title: "The Lord of the Rings: The Return of the King"
    summary: "Gandalf and Aragorn lead the world of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring."
    sort_title: Lord of the Rings 3



# ####################
# GODZILLA
# ####################

  Gojira: #-- Godzilla
    title: Godzilla
    match:
      mapping_id: 1678
      year: 1954
    sort_title: Godzilla 1

  Godzilla vs. Biollante:
    summary: Concerned over Godzilla's possible return after the previous attack, the Japanese government uses his cells to create a new bioweapon, Anti-Nuclear Energy Bacteria. They enlist geneticist Genshiro Shiragami, whose experiments result in a new monstrous mutation.
  Godzilla vs. SpaceGodzilla:
    summary: "Godzilla is threatened by two new forces: Mogera (another UN-built machine), and SpaceGodzilla - an extraterrestrial beast spawned when Godzilla's cells were carried into space by Mothra and warped by a black hole."

  "Godzilla 2000: Millennium":
    summary: Godzilla is a literal force of nature to Japan. Scientists find a sixty-million-year-old UFO deep in the Japan Trench. As they attempt to raise the UFO to study it, it takes off into the sky on its own, searching for genetic information that only Godzilla possesses.
  Godzilla vs. Megaguirus:
    summary: In an alternate timeline, the original Godzilla was never defeated and now repeatedly re-emerges to feed on Japan's energy sources. A new inter-dimensional weapon called the Dimension Tide is created to eliminate Godzilla... however, the new weapon might also serve as a gateway to something far more sinister.
  Giant Monsters All-Out Attack:
    alt_title: "Godzilla, Mothra and King Ghidorah: Giant Monsters All-Out Attack"
    summary: Ignoring all prior movies except the original, Godzilla is a distant memory for Japan when the destruction of a US submarine raises alarms. The ancient guardian monsters must rise to protect Japan against the vengeful spirits within Godzilla that seek revenge for the suffering Japan inflicted in the Pacific conflict.
  Godzilla Against MechaGodzilla:
    summary: When a new Godzilla emerges, a cyborg version named Kiryu is constructed from the remains of the 1954 monster. The machine is discovered to harbor the restless soul of the original Godzilla as JSDF pilot Akane Yashiro must learn to find value in her own life as well.
  "Godzilla: Tokyo S.O.S.":
    summary: In this sequel to "Godzilla Against MechaGodzilla", Mothra and her fairies return to Japan to warn mankind that Kiryu must be returned to the sea, for the dead must not be disturbed. However, Godzilla has survived to menace Japan, leaving MechaGodzilla as the nation's only defense.
  "Godzilla: Final Wars":
    summary: "Ignoring all prior movies from this era, humanity finally imprisons Godzilla in the South Pole. All is peaceful until monsters emerge to lay waste to Earth's cities. A race of benevolent aliens known as Xiliens arrive to help, but not all is what it seems with these bizarre visitors. If humanity wishes to survive, they must reluctantly resurrect their most hated enemy: Godzilla."

  Shin Godzilla:
    originally_available: 2016-10-11
  Shin Godzilla Orthochromatic:
    match:
      title: Shin Godzilla
      edition: Orthochromatic
    sort_title: Godzilla 2016 Ortho
    originally_available: 2023-07-14
  Godzilla Minus One Minus Color:
    match:
      title: Godzilla Minus One
      edition: Minus Color
    sort_title: Godzilla 2023 2
    summary: Post war Japan is at its lowest point when a new crisis emerges in the form of a giant monster, baptized in the horrific power of the atomic bomb. Painstakingly re-colored into monochrome to recreate the feeling of an early 1950s kaiju movie.
    originally_available: 2024-01-26

  Godzilla (1998):
    match:
      title: Godzilla
      year: 1998
    title: Godzilla
    sort_title: Godzilla Zilla98

# ####################

  The Crimes of Grindelwald:
    match:
      mapping_id: 338952
    alt_title: "Fantastic Beasts: The Crimes of Grindelwald"
  The Secrets of Dumbledore:
    match:
      mapping_id: 338953
    alt_title: "Fantastic Beasts: The Secrets of Dumbledore"

# ####################

  Pitch Black:
    sort_title: Chronicles of Riddick 1
  Dark Fury:
    match:
      mapping_id: 2791
    alt_title: "The Chronicles of Riddick: Dark Fury"
    sort_title: Chronicles of Riddick 1.5
  The Chronicles of Riddick:
    match:
      mapping_id: 2789
    sort_title: Chronicles of Riddick 2
  Riddick:
    match:
      mapping_id: 87421
    sort_title: Chronicles of Riddick 3

# ####################
# JURASSIC PARK
# ####################

  Jurassic Park:
    sort_title: Jurassic Park 1
  "The Lost World: Jurassic Park": 
    sort_title: Jurassic Park 2
  Jurassic Park III: 
    sort_title: Jurassic Park 3
  Jurassic World: 
    sort_title: Jurassic World 1
  "Jurassic World: Fallen Kingdom": 
    sort_title: Jurassic World 2
  Battle at Big Rock: 
    sort_title: Jurassic World 2.5
  Jurassic World Dominion: 
    alt_title: "Jurassic World: Dominion"
    sort_title: Jurassic World 3


# ####################
# DC
# ####################

  Batman Returns:
    summary: "While Batman deals with a deformed man calling himself the Penguin, an employee of a corrupt businessman transforms into the Catwoman."
  Batman Forever:
    summary: "Batman must battle a disfigured district attorney and a disgruntled former employee with help from an amorous psychologist and a young circus acrobat."
  "Batman & Robin":
    summary: "Batman and Robin try to keep their relationship together even as they must stop Mr. Freeze and Poison Ivy from freezing Gotham City."

  The Batman:
    match:
      year: 2022
    sort_title: Batman 2022

# ####################

  "Gamera, the Giant Monster":
    match:
      mapping_id: 21930
    originally_available: 1965-11-27
  "Gamera: Guardian of the Universe":
    match:
      mapping_id: 54433
    originally_available: 1995-03-11
    summary: "A monstrous new species of bird appears just as a teenage girl is gifted an amulet that was found on a mysterious atoll. As the creatures begin to attack, an ancient guardian emerges."
  "Gamera 2: Attack of Legion":
    match:
      mapping_id: 59480
    originally_available: 1996-07-12
    summary: "A meteor lands in Japan and unleashes hundreds of insect-like 'Legion' creatures. Gamera shows up to deal with the ever-evolving adversary, but the battle may result in him losing his bond with humanity."
  "Gamera 3: Revenge of Iris":
    match:
      mapping_id: 60159
    originally_available: 1999-03-06
    summary: "Gamera's ties to humanity have been severed as the monstrous Gyaos re-emerge. An orphaned girl named Ayana discovers a new creature she names Iris, and seeks revenge on Gamera for the death of her family."

  Gamera:
    match:
      title: Gamera
      year: 2015
    edition: Short Film


# ####################

  "Mission: Impossible - Dead Reckoning Part One":
    match:
      title: 
        - "Mission: Impossible - Dead Reckoning"
        - "Mission: Impossible - Dead Reckoning Part One"
    title: "Mission: Impossible - Dead Reckoning Part One"

  Princess Mononoke:
    match:
      mapping_id: 128
    originally_available: 1997-07-12
    summary: "Ashitaka is cursed by a demonized boar god and must journey to the west to find a cure. Along the way, he meets San, a human woman fighting to protect the forest, and Lady Eboshi, who is trying to destroy it."


