metadata:
  The Phantom Menace:
    alt_title: "Star Wars: Episode I - The Phantom Menace"
    year: 1999
    sort_title: Star Wars 1
    label: Star Wars
  Attack of the Clones:
    alt_title: "Star Wars: Episode II - Attack of the Clones"
    year: 2002
    sort_title: Star Wars 2
    label: Star Wars
  Revenge of the Sith:
    alt_title: "Star Wars: Episode III - Revenge of the Sith"
    year: 2005
    sort_title: Star Wars 3
    label: Star Wars
  A New Hope:
    alt_title: "Star Wars"
    year: 1977
    sort_title: Star Wars 4
    label: Star Wars
  The Empire Strikes Back:
    alt_title: "Star Wars: Episode V - The Empire Strikes Back"
    year: 1980
    sort_title: Star Wars 5
    label: Star Wars
  Return of the Jedi:
    alt_title: "Star Wars: Episode VI - Return of the Jedi"
    year: 1983
    sort_title: Star Wars 6
    label: Star Wars
  The Force Awakens:
    alt_title: "Star Wars: The Force Awakens"
    year: 2015
    sort_title: Star Wars 7
    label: Star Wars
  The Last Jedi:
    alt_title: "Star Wars: The Last Jedi"
    year: 2017
    sort_title: Star Wars 8
    label: Star Wars
  The Rise of Skywalker:
    alt_title: "Star Wars: The Rise of Skywalker"
    year: 2019
    sort_title: Star Wars 9
    label: Star Wars
  Solo:
    alt_title: "Solo: A Star Wars Story"
    year: 2018
    sort_title: Star Wars 3.5
    label: Star Wars
  Rogue One:
    alt_title: "Rogue One: A Star Wars Story"
    year: 2016
    sort_title: Star Wars 3.9
    label: Star Wars
  "Obi-Wan Kenobi - The Patterson Cut":
    alt_title: "Obi-Wan Kenobi: The Patterson Cut"
    year: 2022
    sort_title: Star Wars 3.1
    collection: Star Wars
    label: Star Wars
    tmdb_show: 92830
  "The Fellowship of the Ring":
    title: "The Lord of the Rings: The Fellowship of the Ring"
    year: 2001
    original_title: "The Lord of the Rings: The Fellowship of the Ring"
    summary: "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron."
    sort_title: LOTR 1
  "The Two Towers":
    title: "The Lord of the Rings: The Two Towers"
    year: 2002
    original_title: "The Lord of the Rings: The Two Towers"
    summary: "While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron's new ally, Saruman, and his hordes of Isengard."
    sort_title: LOTR 2
  "The Return of the King":
    title: "The Lord of the Rings: The Return of the King"
    year: 2003
    original_title: "The Lord of the Rings: The Return of the King"
    summary: "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring."
    sort_title: LOTR 3
  "The Hobbit: An Unexpected Journey":
    year: 2012
    sort_title: Hobbit 1
  "The Hobbit: The Desolation of Smaug":
    year: 2013
    sort_title: Hobbit 2
  "The Hobbit: The Battle of the Five Armies":
    alt_title: "The Hobbit: The Battle of Five Armies"
    year: 2014
    sort_title: Hobbit 3
  The Matrix:
    sort_title: Matrix 1
  The Animatrix:
    sort_title: Matrix 1.5
  The Matrix Reloaded:
    sort_title: Matrix 2
  The Matrix Revolutions:
    sort_title: Matrix 3
  The Matrix Resurrections:
    sort_title: Matrix 4
  Godzilla (1954):
    title: Godzilla
    year: 1954
    sort_title: Godzilla 1954
    collection.remove: "Godzilla (Showa)"
  Godzilla (2014):
    title: Godzilla
    year: 2014
    sort_title: Godzilla MV 2014
    label: Godzilla,MonsterVerse
  GodzillaKOTM:
    title: 'Godzilla: King of the Monsters'
    year: 2019
    sort_title: Godzilla MV 2019
    label: Godzilla,MonsterVerse
  Godzilla vs. Kong:
    title: Godzilla vs. Kong
    year: 2021
    sort_title: Godzilla MV 2021
    label: Godzilla,MonsterVerse
  Shin Godzilla:
    sort_title: Godzilla Shin 2016
    content_rating: R
    label: Godzilla
  KongSkullIsland:
    title: "Kong: Skull Island"
    year: 2017
    label: King Kong,MonsterVerse
    sort_title: Kong MV 2017
  "Godzilla: Planet of the Monsters":
    year: 2017
    sort_title: Godzilla zAnime 1
    label: Godzilla,Anime
  "Godzilla: City on the Edge of Battle":
    year: 2018
    sort_title: Godzilla zAnime 2
    label: Godzilla,Anime
  "Godzilla: The Planet Eater":
    year: 2018
    sort_title: Godzilla zAnime 3
    label: Godzilla,Anime
  Harakiri:
    year: 1962
    label: Samurai
  Morbius:
    year: 2022
    label: MCEU
  The Crimes of Grindelwald:
    alt_title: "Fantastic Beasts: The Crimes of Grindelwald"
  The Secrets of Dumbledore:
    alt_title: "Fantastic Beasts: The Secrets of Dumbledore"
  Pitch Black:
    sort_title: Riddick 1
  Dark Fury:
    alt_title: "The Chronicles of Riddick: Dark Fury"
    sort_title: Riddick 1.5
  The Chronicles of Riddick:
    sort_title: Riddick 2
  Riddick:
    sort_title: Riddick 3
  Jurassic Park:
    sort_title: Jurassic Park 1
  "The Lost World: Jurassic Park":
    sort_title: Jurassic Park 2
  Jurassic Park III:
    sort_title: Jurassic Park 3
  Jurassic World:
    sort_title: Jurassic World 1
  "Jurassic World: Fallen Kingdom":
    sort_title: Jurassic World 2
  Battle at Big Rock:
    sort_title: Jurassic World 2.5
  Jurassic World Dominion:
    sort_title: Jurassic World 3
    
