collections:
  "Sarah's Netflix":
    trakt_list: https://trakt.tv/users/tomhenrich/lists/sarah-s-netflix?sort=title,asc
    smart_label: title.asc
    sort_title: "zSarahs Netflix"
    name_mapping: Sarahs Netflix
    item_label: SarahsNetflix
  "Sarah's Unwatched":
    smart_filter:
      all:
        label: SarahsNetflix
        unplayed: true
      sort_by: title.asc
    sort_title: "+Sarahs Unwatched"
    name_mapping: Sarahs Unwatched
  Non-English:
    smart_filter:
      any:
        audio_language.not: English
      sort_by: title.asc
    sort_title: "+Non-English"
  Hitchcock:
    plex_search:
      all:
        director: Alfred Hitchcock
    collection_order: release
    collection_mode: hide_items
  Marvel Cinematic Universe:
    smart_filter:
      any:
        label: MCU
      sort_by: release.asc
  Marvel Extended Universe:
    smart_filter:
      any:
        label: MCEU
      sort_by: title.asc
  Middle Earth:
    smart_filter:
      any:
        label:
          - LOTR
          - Hobbit
          - Middle Earth
      sort_by: release.asc
  MonsterVerse:
    smart_filter:
      any:
        label: MonsterVerse
      sort_by: title.asc
  Universal Monsters:
    smart_filter:
      any:
        label: Universal Monsters
      sort_by: release.asc
    summary: "Showcasing the most iconic monsters in motion picture history, including Dracula, Frankenstein's Monster, the Mummy, the Invisible Man, the Wolf Man, and more!"
  "Star Trek: TOS":
    tmdb_collection: 151
    smart_label: title.asc
    sort_title: "Star Trek C1: TOS"
    item_label: Star Trek, Star Trek TOS
    name_mapping: Star Trek TOS
    collection_mode: hide
  "Star Trek: TNG":
    tmdb_collection: 115570
    smart_label: title.asc
    sort_title: "Star Trek C2: TNG"
    item_label: Star Trek, Star Trek TNG
    name_mapping: Star Trek TNG
    collection_mode: hide
  "Star Trek: Kelvin Timeline":
    tmdb_collection: 115575
    smart_label: title.asc
    sort_title: "Star Trek C3: Kelvin"
    item_label: Star Trek, Star Trek KEL
    name_mapping: Star Trek Kelvin
    collection_mode: hide
