collections:
  "Sarah's Netflix":
    trakt_list: https://trakt.tv/users/tomhenrich/lists/sarah-s-netflix?sort=title,asc
    smart_label: title.asc
    sort_title: "zSarahs Netflix"
    name_mapping: Sarahs Netflix
    item_label: SarahsNetflix
    test: true
  "Sarah's Unwatched":
    smart_filter:
      all:
        label: SarahsNetflix
        unplayed: true
      sort_by: title.asc
    sort_title: "^Sarahs Unwatched"
    name_mapping: Sarahs Unwatched
  Non-English:
    smart_filter:
      any:
        audio_language.not: English
      sort_by: title.asc
    sort_title: "^Non-English"
  Hitchcock:
    plex_search:
      all:
        director: Alfred Hitchcock
    collection_order: release
    collection_mode: hide_items
  Marvel Cinematic Universe:
    smart_filter:
      any:
        label: MCU
      sort_by: release.asc
  Marvel Extended Universe:
    smart_filter:
      any:
        label: MCEU
      sort_by: release.asc
  Middle Earth:
    smart_filter:
      any:
        label:
          - LOTR
          - Hobbit
          - Middle Earth
      sort_by: release.asc
  MonsterVerse:
    smart_filter:
      any:
        label: MonsterVerse
      sort_by: title.asc
  #Star Wars:
  #  trakt_list: https://trakt.tv/users/tomhenrich/lists/star-wars?sort=released,desc
  #  plex_search:
  #    any:
  #      label: Star Wars
  #  collection_order: alpha
  #  test: true
  Universal Monsters:
    smart_filter:
      any:
        label: Universal Monsters
      sort_by: release.asc
    summary: "Showcasing the most iconic monsters in motion picture history, including Dracula, Frankenstein's Monster, the Mummy, the Invisible Man, the Wolf Man, and more!"
