collections:
  "Sarah's Netflix":
    trakt_list: https://trakt.tv/users/tomhenrich/lists/sarah-s-netflix?sort=title,asc
    smart_label: title.asc
    sort_title: "zSarahs Netflix"
    name_mapping: Sarahs Netflix
    item_label: SarahsNetflix
  "Sarah's Unwatched":
    smart_filter:
      all:
        label: SarahsNetflix
        unplayed: true
      sort_by: title.asc
    sort_title: "+Sarahs Unwatched"
    name_mapping: Sarahs Unwatched
  Non-English:
    smart_filter:
      any:
        audio_language.not: English
      sort_by: title.asc
    sort_title: "+Non-English"
  Hitchcock:
    plex_search:
      all:
        director: Alfred Hitchcock
    collection_order: release
    collection_mode: hide_items
  Marvel Cinematic Universe:
    smart_filter:
      any:
        label: MCU
      sort_by: release.asc
  Marvel Extended Universe:
    smart_filter:
      any:
        label: MCEU
      sort_by: title.asc
  MonsterVerse:
    smart_filter:
      any:
        label: MonsterVerse
      sort_by: title.asc
  Universal Monsters:
    smart_filter:
      any:
        label: Universal Monsters
      sort_by: release.asc
    summary: "Showcasing the most iconic monsters in motion picture history, including Dracula, Frankenstein's Monster, the Mummy, the Invisible Man, the Wolf Man, and more!"
  "Star Trek: TOS":
    tmdb_collection_details: 151
    smart_label: title.asc
    sort_title: "Star Trek C1: TOS"
    item_label: Star Trek, Star Trek TOS
    name_mapping: Star Trek TOS
    collection_mode: hide
  "Star Trek: TNG":
    tmdb_collection_details: 115570
    smart_label: title.asc
    sort_title: "Star Trek C2: TNG"
    item_label: Star Trek, Star Trek TNG
    name_mapping: Star Trek TNG
    collection_mode: hide
  "Star Trek: Kelvin Timeline":
    tmdb_collection_details: 115575
    smart_label: title.asc
    sort_title: "Star Trek C3: Kelvin"
    item_label: Star Trek, Star Trek KEL
    name_mapping: Star Trek Kelvin
    collection_mode: hide
  Spider-Man:
    tmdb_collection_details: 556
    name_mapping: "Spider-Man (Raimi)"
    smart_label: title.asc
    sort_title: "Spider-Man 2002"
    collection_mode: hide
  The Amazing Spider-Man:
    tmdb_collection_details: 125574
    name_mapping: Amazing Spider-Man
    smart_label: title.asc
    sort_title: "Spider-Man 2012"
    item_label: MCEU,Spider-Man
    collection_mode: hide
  "Spider-Verse":
    tmdb_collection_details: 573436
    smart_label: title.asc
    item_label: MCEU,Spider-Man
    collection_mode: hide
    minimum_items: 1
  The Hobbit:
    tmdb_collection_details: 121938
    smart_label: title.asc
    item_label: Hobbit
    sort_title: Hobbit
    name_mapping: Hobbit
    collection_mode: hide_items
  The Lord of the Rings:
    tmdb_collection_details: 119
    smart_label: title.asc
    item_label: LOTR
    sort_title: Lord of the Rings
    name_mapping: Lord of the Rings
    collection_mode: hide_items
