collections:
  "Tom's Watchlist":
    trakt_list: https://trakt.tv/users/tomhenrich/watchlist?sort=rank,asc
    smart_label:
      all:
        label: <<smart_label>>
        unplayed: true
    sort_title: "+Toms Watchlist"
    name_mapping: Toms Watchlist
    label: noshare
    minimum_items: 1
  "Sarah's Watchlist":
    trakt_list: 
      - https://trakt.tv/users/tomhenrich/lists/sarah-s-watchlist?sort=title,asc
      - https://trakt.tv/users/nursesawa/watchlist?sort=rank,asc
    smart_label:
      all:
        label: <<smart_label>>
        unplayed: true
      sort_by: title.asc
    sort_title: "+Sarahs Watchlist"
    name_mapping: Sarahs Watchlist
    label: noshare
    minimum_items: 1
  Non-English:
    smart_filter:
      any:
        audio_language.not: English
      sort_by: title.asc
    sort_title: "++Non-English"
  Hitchcock:
    plex_search:
      all:
        director: Alfred Hitchcock
    collection_order: release
    collection_mode: hide_items
  MonsterVerse:
    smart_filter:
      any:
        label: MonsterVerse
      sort_by: title.asc
    summary: The MonsterVerse is an American multimedia franchise and shared fictional universe featuring Godzilla, King Kong, and other Toho monster characters.

  Middle Earth:
    smart_label: title.asc
    item_label: Middle Earth
    template: {name: tmdb, collection: "119,121938"}
    item_label.append: Middle Earth
    summary: "J.R.R. Tolkien's fantasy series following the adventures of Bilbo and Frodo Baggins." 

# STAR TREK

  "Star Trek: TOS":
    tmdb_collection_details: 151
    smart_label: title.asc
    sort_title: "Star Trek C1: TOS"
    item_label: Star Trek, Star Trek TOS
    name_mapping: Star Trek TOS
    collection_mode: hide
  "Star Trek: TNG":
    tmdb_collection_details: 115570
    smart_label: title.asc
    sort_title: "Star Trek C2: TNG"
    item_label: Star Trek, Star Trek TNG
    name_mapping: Star Trek TNG
    collection_mode: hide
  "Star Trek: Kelvin Timeline":
    tmdb_collection_details: 115575
    smart_label: title.asc
    sort_title: "Star Trek C3: Kelvin"
    item_label: Star Trek, Star Trek KEL
    name_mapping: Star Trek Kelvin
    collection_mode: hide

# MARVEL CINEMATIC UNIVERSE
  Marvel Cinematic Universe:
    smart_filter:
      any:
        label: MCU
      sort_by: release.asc
  Marvel Extended Universe:
    smart_filter:
      any:
        label: MCEU
      sort_by: title.asc
    summary: Movies based on Marvel properties but not officially part of the Marvel Cinematic Universe.
  Spider-Man:
    tmdb_collection_details: 556
    name_mapping: "Spider-Man (Raimi)"
    smart_label: title.asc
    sort_title: "Spider-Man 2002"
    collection_mode: hide
  The Amazing Spider-Man:
    tmdb_collection_details: 125574
    name_mapping: Amazing Spider-Man
    smart_label: title.asc
    sort_title: "Spider-Man 2012"
    item_label: MCEU,Spider-Man
    collection_mode: hide
  "Spider-Verse":
    tmdb_collection_details: 573436
    smart_label: title.asc
    item_label: MCEU,Spider-Man
    collection_mode: hide
    minimum_items: 1

# MIDDLE EARTH

  The Hobbit:
    tmdb_collection_details: 121938
    smart_label: title.asc
    item_label: Hobbit
    sort_title: Hobbit
    name_mapping: Hobbit
    collection_mode: hide_items
  The Lord of the Rings:
    tmdb_collection_details: 119
    smart_label: title.asc
    item_label: LOTR
    sort_title: Lord of the Rings
    name_mapping: Lord of the Rings
    collection_mode: hide_items
